-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:14 PM

local QuestID = 2;

-- Modify steps below for gameplay

function QUEST_START(cid)
	-- Quest is already added by previous quest
	Saga.AddStep(cid, QuestID, 201);
	Saga.AddStep(cid, QuestID, 202);
	Saga.AddStep(cid, QuestID, 203);
	-- Saga.QuestStart(cid, QuestID);
	return 0;
end

function QUEST_FINISH(cid)
	-- Start the followup quest.
      -- print("Quest 2 finish");
	return 0;
end

function QUEST_STEP_1(cid)
     if Saga.FindPosition(cid, QuestID, 10046, 8641, -9858, 1) < 1000  then
		Saga.StartEvent(cid, 20210);
		Saga.StepComplete(cid, QuestID, 201);
		return 0;
     end

     return -1; 
end

function QUEST_STEP_2(cid)
    -- Wait for new content
    Saga.StepComplete(cid, QuestID, 202);
    return 0;
end

function QUEST_STEP_3(cid)
    -- Wait for new content
    return -1;
end

function QUEST_CHECK(cid)
	-- Check all steps for progress
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local ret = -1;

	if CurStepID == 201 then
		ret = QUEST_STEP_1(cid);
	elseif CurStepID == 202 then
		ret = QUEST_STEP_2(cid);
	elseif CurStepID == 203 then
		ret = QUEST_STEP_3(cid);
	end

	if ret == 0 then
		QUEST_CHECK(cid);
	end

	return -1;
end

