-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:14 PM

local QuestID = 11;
local ReqClv = 7;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 121;
local RewCxp = 328;
local RewJxp = 128;
local RewWxp = 0; 
local RewItem1 = 1700113; 
local RewItem2 = 0; 
local RewItemCount1 = 3; 
local RewItemCount2 = 0; 
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 1101);
	Saga.AddStep(cid, QuestID, 1102);	
	Saga.AddStep(cid, QuestID, 1103);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	local freeslots = Saga.FreeInventoryCount(cid, 0);
	if freeslots > 0 then
		Saga.GiveZeny(cid, RewZeny);
		Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
		Saga.GiveItem(cid, RewItem1, RewItemCount1 );
		return 0;
	else
		Saga.EmptyInventory(cid);
		return -1;
	end
end

function QUEST_CANCEL(cid)
	-- Do nothing
	return 0;
end

function QUEST_STEP_1(cid)	
	-- Talk with Scacciano Morrigan   
	Saga.AddWaypoint(cid, QuestID, 1101, 1, 1003);      
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);    
	if ret == 1003 then
		Saga.GeneralDialog(cid, 3936);		
		Saga.SubstepComplete(cid,QuestID,StepID,1);
	end	
	
    -- Check if all substeps are completed
    for i = 1, 1 do
         if Saga.IsSubStepCompleted(cid,QuestID,StepID,i) == false then
			return -1;
		 end
    end	
	
    Saga.ClearWaypoints(cid, QuestID); 
    Saga.StepComplete(cid,QuestID,StepID);
	return 0;
end

function QUEST_STEP_2(cid)
	-- Eliminate a Tropical Hydra
	Saga.Eliminate(cid,QuestID,StepID,10050,8,1);
	Saga.Eliminate(cid,QuestID,StepID,10051,8,1);

	-- Find Black Stripe Tunas Belly
	Saga.FindQuestItem(cid,QuestID,StepID,10052,4069,8000,1,2);
	Saga.FindQuestItem(cid,QuestID,StepID,10053,4069,8000,1,2);	
		
    -- Check if all substeps are completed
    for i = 1, 2 do
         if Saga.IsSubStepCompleted(cid,QuestID,StepID,i) == false then
			return -1;
		 end
    end			
		
    Saga.StepComplete(cid,QuestID,StepID);		
	return 0;    
end

function QUEST_STEP_3(cid)
	-- Speak with Scacciano Morrigan
	Saga.AddWaypoint(cid, QuestID, 1103, 1, 1003);      
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);    
	if ret == 1003 then
		Saga.GeneralDialog(cid, 3936);	
		Saga.NpcTakeItem(cid, 4069, 1);	
		Saga.SubstepComplete(cid,QuestID,StepID,1);
	end	
	
    -- Check if all substeps are completed
    for i = 1, 1 do
         if Saga.IsSubStepCompleted(cid,QuestID,StepID,i) == false then
			return -1;
		 end
    end	
	
    Saga.ClearWaypoints(cid, QuestID); 
    Saga.StepComplete(cid,QuestID,StepID);
    Saga.QuestComplete(cid, QuestID);	        
	return -1;		
end

function QUEST_CHECK(cid)
	-- Check all steps for progress
	local CurStepID = Saga.GetStepIndex(cid, QuestID );
	local ret = -1;
	StepID = CurStepID;
	
	if CurStepID == 1101 then
		ret = QUEST_STEP_1(cid);
	elseif CurStepID == 1102 then
		ret = QUEST_STEP_2(cid);
	elseif CurStepID == 1103 then
		ret = QUEST_STEP_3(cid);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end

