-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:14 PM

local QuestID = 14;
local ReqClv = 8;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 210;
local RewCxp = 408;
local RewJxp = 160;
local RewWxp = 0;
local RewItem1 = 1700113;
local RewItem2 = 2668;
local RewItemCount1 = 5;
local RewItemCount2 = 1;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_VERIFY(cid)
	Saga.GeneralDialog(cid, 3957);
	return 0;
end

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 1401);
	Saga.AddStep(cid, QuestID, 1402);
	Saga.InsertQuest(cid, QuestID, 2);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	local freeslots = Saga.FreeInventoryCount(cid, 0);
	if freeslots > 1 then
		Saga.GiveZeny(cid, RewZeny);
		Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
		Saga.GiveItem(cid, RewItem1, RewItemCount1);
		Saga.GiveItem(cid, RewItem2, RewItemCount2);
		return 0;
	else
		Saga.EmptyInventory(cid);
		return -1;
	end
end

function QUEST_CANCEL(cid)
	return 0;
end


function QUEST_STEP_1(cid, StepID)
	--Capture a KuiKui;Obtain PuiPui's Petal;Loot Black Stripe Tuna Belly
	Saga.FindQuestItem(cid, QuestID, StepID, 10008, 2654, 8000, 3, 1);
	Saga.FindQuestItem(cid, QuestID, StepID, 10009, 2655, 8000, 1, 2);
	Saga.FindQuestItem(cid, QuestID, StepID, 10010, 2655, 8000, 1, 2);
	Saga.FindQuestItem(cid, QuestID, StepID, 10052, 4069, 8000, 2, 3);
	Saga.FindQuestItem(cid, QuestID, StepID, 10053, 4069, 8000, 2, 3);

	-- check if all substeps are completed
	for i = 1, 3 do
	if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Deliver material to Averro Reinhold
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1004);

	--check for completion
	local ItemCountA = Saga.CheckUserInventory(cid, 2654);
	local ItemCountB = Saga.CheckUserInventory(cid, 2655);
	local ItemCountC = Saga.CheckUserInventory(cid, 4069);
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1004 then
		Saga.GeneralDialog(cid, 3936);
		if ItemCountA > 2 and ItemCountB > 0 and ItemCountC > 1 then
			Saga.NpcTakeItem(cid, 2654, 3);
			Saga.NpcTakeItem(cid, 2655, 1);
			Saga.NpcTakeItem(cid, 4069, 2);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	end

	--check if all substeps are complete
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end


function QUEST_CHECK(cid)
	-- Check all steps for progress
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local ret = -1;
	local StepID = CurStepID;
	
	if CurStepID == 1401 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 1402 then
		ret = QUEST_STEP_2(cid, StepID);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end

	
