-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:14 PM

-- En-tête du fichier avec initialisation des variables

local QuestID = 140;
local ReqClv = 9;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 152;
local RewCxp = 519;
local RewJxp = 204;
local RewWxp = 0; 
local RewItem1 = 1700113; 
local RewItem2 = 0; 
local RewItemCount1 = 2; 
local RewItemCount2 = 0; 

function QUEST_VERIFY(cid)
	Saga.GeneralDialog(cid, 3957);
	return 0;
end

-- Initialisation des étapes
function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 14001);
	Saga.AddStep(cid, QuestID, 14002);
	Saga.AddStep(cid, QuestID, 14003);
	Saga.AddStep(cid, QuestID, 14004);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Récompenses
	local freeslots = Saga.FreeInventoryCount(cid, 0)
	if freeslots > 0 then
		return 0;
	else
		Saga.EmptyInventory(cid);
		return -1;
	end
end

function QUEST_CANCEL(cid)
	-- Annulation de la quête
	return 0;
end

function QUEST_STEP_1(cid)
	-- Lancement des étapes
	
	-- Vérifie que l'on parle au Npc
	
    -- Vérifie si l'étape en cours est terminé
	
	Saga.StepComplete(cid, QuestID, StepID);
	return 0
end

function QUEST_STEP_2(cid)
	-- Lancement des étapes
	
	-- Vérifie que l'on parle au Npc
	
    -- Vérifie si l'étape en cours est terminé
	
	Saga.StepComplete(cid, QuestID, StepID);
    return 0;
end

function QUEST_STEP_3(cid)
	-- Lancement des étapes
	
	-- Vérifie que l'on parle au Npc
	
    -- Vérifie si l'étape en cours est terminé

	Saga.StepComplete(cid, QuestID, StepID);
    return 0;
end

function QUEST_STEP_4(cid)
	-- Lancement des étapes
	
	-- Vérifie que l'on parle au Npc
	
    -- Vérifie si l'étape en cours est terminé
	
	Saga.StepComplete(cid, QuestID, StepID);
    Saga.QuestComplete(cid, QuestID);
    return -1;
end

function QUEST_CHECK(cid)
	-- Vérifie toutes les étapes
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local ret = -1;
	StepID = CurStepID;
	
	if CurStepID == 14001 then
		ret = QUEST_STEP_1(cid);
	elseif CurStepID == 14002 then
		ret = QUEST_STEP_2(cid);
	elseif CurStepID == 14003 then
		ret = QUEST_STEP_3(cid);
	elseif CurStepID == 14004 then
		ret = QUEST_STEP_4(cid);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid)
	end
	
	return ret;
end