-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:15 PM

local QuestID = 159;
local ReqClv = 12;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 212;
local RewCxp = 675;
local RewJxp = 0;
local RewWxp = 0;
local RewItem1 = 1700113;
local RewItem2 = 0;
local RewItemCount1 = 2;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 15901);
	Saga.AddStep(cid, QuestID, 15902);
	Saga.AddStep(cid, QuestID, 15903);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	Saga.GiveItem(cid, RewItem1, RewItemCount1);
	Saga.GiveZeny(cid, RewZeny);
	Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
	return 0;
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Talk with Hollgran
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1011);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1011 then
		Saga.GeneralDialog(cid, 2545);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)

	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1012);	 -- Visit Monika Reynolds;
	Saga.AddWaypoint(cid, QuestID, StepID, 2, 1010);	 -- Regina Salisbury;
	Saga.AddWaypoint(cid, QuestID, StepID, 3, 1013);	 -- Pelshia Hiltrud;
	Saga.AddWaypoint(cid, QuestID, StepID, 4, 1009);	 -- Volker Stanwood;
	Saga.AddWaypoint(cid, QuestID, StepID, 5, 1006);	 -- Mainhared Anselm;
	Saga.AddWaypoint(cid, QuestID, StepID, 6, 1007);	 -- Magnet Wilhelmina;
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1012 then
		Saga.GeneralDialog(cid, 2548);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	elseif ret == 1010 then
		Saga.GeneralDialog(cid, 2551);
		Saga.SubstepComplete(cid, QuestID, StepID, 2);
	elseif ret == 1013 then
		Saga.GeneralDialog(cid, 2554);
		Saga.SubstepComplete(cid, QuestID, StepID, 3);
	elseif ret == 1009 then
		Saga.GeneralDialog(cid, 2557);
		Saga.SubstepComplete(cid, QuestID, StepID, 4);
	elseif ret == 1006 then
		Saga.NpcGiveItem(cid, 2786, 1);
		Saga.GeneralDialog(cid, 2560);
		Saga.SubstepComplete(cid, QuestID, StepID, 5);
	elseif ret == 1007 then
		Saga.NpcGiveItem(cid, 2787, 1);
		Saga.GeneralDialog(cid, 2563);
		Saga.SubstepComplete(cid, QuestID, StepID, 6);
	end
	
	-- Check if all substeps are completed
	for i = 1, 6 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_3(cid, StepID)
	-- Talk with Hollgran
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1011);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1011 then
		Saga.GeneralDialog(cid, 2566);
		local ItemCountA = Saga.CheckUserInventory(cid, 2786);
		local ItemCountB = Saga.CheckUserInventory(cid, 2787);
		if ItemCountA > 0 and ItemCountB > 0 then
			Saga.NpcTakeItem(cid, 2786, 1);
			Saga.NpcTakeItem(cid, 2787, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local StepID = CurStepID;
	local ret = -1;

	if CurStepID == 15901 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 15902 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 15903 then
		ret = QUEST_STEP_3(cid, StepID);
	end

	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
