-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:14 PM

local QuestID = 16;
local ReqClv = 11;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 408;
local RewCxp = 310;
local RewJxp = 0;
local RewWxp = 0;
local RewItem1 = 1700113;
local RewItem2 = 0;
local RewItemCount1 = 10;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	-- Initialize all quest steps
	-- Initialize all starting navigation points
	Saga.AddStep(cid, QuestID, 1601);
	Saga.AddStep(cid, QuestID, 1602);
	Saga.AddStep(cid, QuestID, 1603);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Check for free inventory slot
	local freeslots = Saga.FreeInventoryCount(cid, 0);
	if freeslots > 1 then
		-- Handout all rewards
		Saga.GiveZeny(cid, RewZeny);
		Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
		Saga.GiveItem(cid, RewItem1, RewItemCount1);
		Saga.GiveItem(cid, RewItem2, RewItemCount2);
		return 0;
	else
		Saga.EmptyInventory(cid);
		return -1;
	end
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid)
	-- Talk to adriana
	Saga.AddWaypoint(cid, QuestID, 1601, 1, 1002);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1002 then
		Saga.GeneralDialog(cid, 28);
		Saga.SubstepComplete(cid, QuestID, 1601, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, 1601, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, 1601);
	return 0;
end

function QUEST_STEP_2(cid)
	-- eliminate boss pukui
	Saga.Eliminate(cid, QuestID, 1602, 10011, 1, 1);
	
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, 1602, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, 1602);
	return 0;
end


function QUEST_STEP_3(cid)
	-- Talk to zarko
	Saga.AddWaypoint(cid, QuestID, 1603, 1, 1005);
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1005 then
		Saga.GeneralDialog(cid, 28);
		Saga.SubstepComplete(cid, QuestID, 1603, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, 1603, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, 1603);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	-- Check all steps for progress
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local ret = -1;
	StepID = CurStepID;
	
	if CurStepID == 1601 then
		ret = QUEST_STEP_1(cid);
	elseif CurStepID == 1602 then
		ret = QUEST_STEP_2(cid);
	elseif CurStepID == 1603 then
		ret = QUEST_STEP_3(cid);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
