-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:15 PM

local QuestID = 161;
local ReqClv = 12;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 212;
local RewCxp = 675;
local RewJxp = 0;
local RewWxp = 0;
local RewItem1 = 1700113;
local RewItem2 = 0;
local RewItemCount1 = 2;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 16101);
	Saga.AddStep(cid, QuestID, 16102);
	Saga.AddStep(cid, QuestID, 16103);
	Saga.InsertQuest(cid, QuestID, 2);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	Saga.GiveItem(cid, RewItem1, RewItemCount1);
	Saga.GiveZeny(cid, RewZeny);
	Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
	return 0;
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Talk to ?
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1011);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1011 then
		Saga.GeneralDialog(cid, 2569);
		Saga.SubstepComplete(cid, QuestID, 501, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, 501, i) == false then
			return -1;
		end
	end
	
	-- Clear waypoints
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, 501);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Talk with Lothair Eaton
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1079);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1079 then
		Saga.GeneralDialog(cid, 2572);
		Saga.NpcGiveItem(cid, 3974, 1);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_3(cid, StepID)
	-- Deliver Eye-Glasses to Orak Edith
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1099);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1099 then
		Saga.GeneralDialog(cid, 2575);
		local ItemCountA = Saga.CheckUserInventory(cid, 3972);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 3972, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local StepID = CurStepID;
	local ret = -1;

	if CurStepID == 16101 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 16103 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 16103 then
		ret = QUEST_STEP_3(cid, StepID);
	end
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
