-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:16 PM

local QuestID = 216;
local ReqClv = 14;
local ReqJlv = 0;
local NextQuest = 217;
local RewZeny = 252;
local RewCxp = 912;
local RewJxp = 0;
local RewWxp = 0;
local RewItem1 = 1700113;
local RewItem2 = 0;
local RewItemCount1 = 3;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 21601);
	Saga.AddStep(cid, QuestID, 21602);
	Saga.AddStep(cid, QuestID, 21603);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	Saga.GiveItem(cid, RewItem1, RewItemCount1);
	Saga.GiveZeny(cid, RewZeny);
	Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Talk with Mitzi
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1081);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1081 then
		Saga.GeneralDialog(cid, 3066);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Obtain Butchered Beef (8)
	Saga.FindQuestItem(cid, QuestID, StepID, 10120, 4005, 8000, 8, 1);
	Saga.FindQuestItem(cid, QuestID, StepID, 10121, 4005, 8000, 8, 1);
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_3(cid, StepID)
	-- Report to Mitzi
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1081);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1081 then
		Saga.GeneralDialog(cid, 3069);
	
		local ItemCountA = Saga.CheckUserInventory(cid, 4005);
		if ItemCountA > 7 then
			Saga.NpcTakeItem(cid, 4005, 8);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local StepID = CurStepID;
	local ret = -1;

	if CurStepID == 21601 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 21602 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 21603 then
		ret = QUEST_STEP_3(cid, StepID);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
