-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:16 PM

local QuestID = 226;
local ReqClv = 14;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 347;
local RewCxp = 1701;
local RewJxp = 668;
local RewWxp = 0;
local RewItem1 = 1700113;
local RewItem2 = 0;
local RewItemCount1 = 6;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 22601);
	Saga.AddStep(cid, QuestID, 22602);
	Saga.AddStep(cid, QuestID, 22603);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	Saga.GiveItem(cid, RewItem1, RewItemCount1);
	Saga.GiveZeny(cid, RewZeny);
	Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
	return 0;
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Talk with Regina Salisbury
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1010);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1010 then
		Saga.GeneralDialog(cid, 3144);
		local freeslots = Saga.FreeInventoryCount(cid, 0);
		if freeslots > 1 then
			Saga.NpcGiveItem(cid, 4016, 1);
			Saga.NpcGiveItem(cid, 4017, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Deliver 'Present' to Mitzi;
	-- Deliver 'Present' to Achim;
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1081);
	Saga.AddWaypoint(cid, QuestID, StepID, 2, 1080);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1081 then
		Saga.GeneralDialog(cid, 3150);
	
		local ItemCountA = Saga.CheckUserInventory(cid, 4016);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4016, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	elseif ret == 1080 then
		Saga.GeneralDialog(cid, 3147);
	
		local ItemCountA = Saga.CheckUserInventory(cid, 4017);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4017, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 2);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 2 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_3(cid, StepID)
	-- Report to Regina Salisbury
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1010);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1010 then
		Saga.GeneralDialog(cid, 3153);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local StepID = CurStepID;
	local ret = -1;

	if CurStepID == 22601 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 22602 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 22603 then
		ret = QUEST_STEP_3(cid, StepID);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
