-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:18 PM

local QuestID = 370;
local ReqClv = 25;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 1224;
local RewCxp = 3383;
local RewJxp = 0;
local RewWxp = 0;
local RewItem1 = 0;
local RewItem2 = 0;
local RewItemCount1 = 0;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 37001);
	Saga.AddStep(cid, QuestID, 37002);
	Saga.AddStep(cid, QuestID, 37003);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	Saga.GiveItem(cid, RewItem1, RewItemCount1);
	Saga.GiveZeny(cid, RewZeny);
	Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
	return 0;
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Talk with Gretchel Ortrud
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1025);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1025 then
		Saga.GeneralDialog(cid, 3690);
	
		local freeslots = Saga.FreeInventoryCount(cid, 0);
		if freeslots > 0 then
			Saga.NpcGiveItem(cid, 4186, 4);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Deliver bread to Chayenne;
	-- Deliver bread to Derek;
	-- Deliver bread to Moritz Blauveltto;
	-- Deliver bread to Pretan;
	
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1022);
	Saga.AddWaypoint(cid, QuestID, StepID, 2, 1021);
	Saga.AddWaypoint(cid, QuestID, StepID, 3, 1026);
	Saga.AddWaypoint(cid, QuestID, StepID, 4, 1024);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1022 then
		Saga.GeneralDialog(cid, 3693);
	
		local ItemCountA = Saga.CheckUserInventory(cid, 4186);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4186, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	elseif ret == 1021 then
		Saga.GeneralDialog(cid, 3585);

		local ItemCountA = Saga.CheckUserInventory(cid, 4186);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4186, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	elseif ret == 1026 then
		Saga.GeneralDialog(cid, 3696);

		local ItemCountA = Saga.CheckUserInventory(cid, 4186);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4186, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	elseif ret == 1024 then
		Saga.GeneralDialog(cid, 3699);

		local ItemCountA = Saga.CheckUserInventory(cid, 4186);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4186, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 4 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_3(cid, StepID)
	-- Talk with Gretchel Ortrud
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1025);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1025 then
		Saga.GeneralDialog(cid, 3702);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local StepID = CurStepID;
	local ret = -1;

	if CurStepID == 37001 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 37002 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 37003 then
		ret = QUEST_STEP_3(cid, StepID);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
