-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:18 PM

local QuestID = 389;
local ReqClv = 21;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 763;
local RewCxp = 3654;
local RewJxp = 1462;
local RewWxp = 0;
local RewItem1 = 1700114;
local RewItem2 = 0;
local RewItemCount1 = 4;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 38901);
	Saga.AddStep(cid, QuestID, 38902);
	Saga.AddStep(cid, QuestID, 38903);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	Saga.GiveItem(cid, RewItem1, RewItemCount1);
	Saga.GiveZeny(cid, RewZeny);
	Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
	return 0;
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Talk with Volker Stanwood
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1009);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1009 then
		Saga.GeneralDialog(cid, 3849);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Eliminate Culvert Thief Bug Female
	-- Eliminate Culvert Thief Bug Male;
	
	Saga.Eliminate(cid, QuestID, StepID, 10139, 5, 1);
	Saga.Eliminate(cid, QuestID, StepID, 10140, 5, 1);
	Saga.Eliminate(cid, QuestID, StepID, 10141, 5, 2);
	Saga.Eliminate(cid, QuestID, StepID, 10142, 5, 2);
	
	-- Check if all substeps are completed
	for i = 1, 2 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_3(cid, StepID)
	-- Talk with Volker Stanwood
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1009);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1009 then
		Saga.GeneralDialog(cid, 3852);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local StepID = CurStepID;
	local ret = -1;

	if CurStepID == 38901 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 38902 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 38903 then
		ret = QUEST_STEP_3(cid, StepID);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
