-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:18 PM

local QuestID = 417;
local ReqClv = 25;
local ReqJlv = 0;
local NextQuest = 0;
local RewZeny = 1224;
local RewCxp = 4510;
local RewJxp = 1804;
local RewWxp = 0;
local RewItem1 = 0;
local RewItem2 = 0;
local RewItemCount1 = 0;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 41701);
	Saga.AddStep(cid, QuestID, 41702);
	Saga.AddStep(cid, QuestID, 41703);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
		Saga.GiveZeny(cid, RewZeny);
		Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
		return 0;
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Visit Monika Reynolds
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1012);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1012 then
		Saga.GeneralDialog(cid, 4644);
		Saga.SubstepComplete(cid, QuestID, StepID, 1);
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	-- Clear waypoints
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Visit Ireyneal
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1023);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1023 then
		Saga.GeneralDialog(cid, 4647);

		local freeslots = Saga.FreeInventoryCount(cid, 0);
		if freeslots > 0 then
			Saga.NpcGiveItem(cid, 4225, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		else
			Saga.EmptyInventory(cid);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	-- Clear waypoints
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end


function QUEST_STEP_3(cid, StepID)
	-- Deliver letter to Ruud
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1190);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1190 then
		Saga.GeneralDialog(cid, 4650);
	
		local ItemCountA = Saga.CheckUserInventory(cid, 4225);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4225, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		else
			Saga.ItemNotFound(cid);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	-- Clear waypoints
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end


function QUEST_CHECK(cid)
	-- Check all steps for progress
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local ret = -1;
	local StepID = CurStepID;
	
	if CurStepID == 41701 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 41702 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 41703 then
		ret = QUEST_STEP_3(cid, StepID);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
