-- Saga is Licensed under Creative Commons Attribution-NonCommerial-ShareAlike 3.0 License
-- http://creativecommons.org/licenses/by-nc-sa/3.0/
-- Generated By Quest Extractor on 2/8/2008 3:46:18 PM

local QuestID = 427;
local ReqClv = 31;
local ReqJlv = 0;
local NextQuest = 428;
local RewZeny = 1199;
local RewCxp = 7860;
local RewJxp = 3132;
local RewWxp = 0;
local RewItem1 = 1700115;
local RewItem2 = 0;
local RewItemCount1 = 2;
local RewItemCount2 = 0;
local StepID = 0;

-- Modify steps below for gameplay

function QUEST_START(cid)
	Saga.AddStep(cid, QuestID, 42701);
	Saga.AddStep(cid, QuestID, 42702);
	Saga.AddStep(cid, QuestID, 42703);
	Saga.InsertQuest(cid, QuestID, 1);
	return 0;
end

function QUEST_FINISH(cid)
	-- Gives all rewards
	local freeslots = Saga.FreeInventoryCount(cid, 0);
	if freeslots > 0 then
		Saga.GiveZeny(cid, RewZeny);
		Saga.GiveExp(cid, RewCxp, RewJxp, RewWxp);
		Saga.GiveItem(cid, RewItem1, RewItemCount1);
		return 0;
	else
		Saga.EmptyInventory(cid);
		return -1;
	end
end

function QUEST_CANCEL(cid)
	return 0;
end

function QUEST_STEP_1(cid, StepID)
	-- Receive 'Goods' from Portman
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1135);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1135 then
		Saga.GeneralDialog(cid, 4718);

		local freeslots = Saga.FreeInventoryCount(cid, 0);
		if freeslots > 0 then
			Saga.NpcGiveItem(cid, 4236, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		else
			Saga.EmptyInventory(cid);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	-- Clear waypoints
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_2(cid, StepID)
	-- Visit Moritz Blauvelt
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1026);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1026 then
		Saga.GeneralDialog(cid, 4721);
	
		local ItemCountA = Saga.CheckUserInventory(cid, 4236);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4236, 1);
			Saga.NpcGiveItem(cid, 4237, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		else
			Saga.ItemNotFound(cid);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	-- Clear waypoints
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	return 0;
end

function QUEST_STEP_3(cid, StepID)
	-- Deliver 'Goods' to Aili
	Saga.AddWaypoint(cid, QuestID, StepID, 1, 1028);
	
	-- Check for completion
	local ret = Saga.GetNPCIndex(cid);
	if ret == 1028 then
		Saga.GeneralDialog(cid, 4724);
	
		local ItemCountA = Saga.CheckUserInventory(cid, 2630);
		if ItemCountA > 0 then
			Saga.NpcTakeItem(cid, 4237, 1);
			Saga.SubstepComplete(cid, QuestID, StepID, 1);
		else
			Saga.ItemNotFound(cid);
		end
	end
	
	-- Check if all substeps are completed
	for i = 1, 1 do
		if Saga.IsSubStepCompleted(cid, QuestID, StepID, i) == false then
			return -1;
		end
	end
	
	-- Clear waypoints
	Saga.ClearWaypoints(cid, QuestID);
	Saga.StepComplete(cid, QuestID, StepID);
	Saga.QuestComplete(cid, QuestID);
	return -1;
end

function QUEST_CHECK(cid)
	-- Check all steps for progress
	local CurStepID = Saga.GetStepIndex(cid, QuestID);
	local ret = -1;
	local StepID = CurStepID;
	
	if CurStepID == 42701 then
		ret = QUEST_STEP_1(cid, StepID);
	elseif CurStepID == 42702 then
		ret = QUEST_STEP_2(cid, StepID);
	elseif CurStepID == 42703 then
		ret = QUEST_STEP_3(cid, StepID);
	end
	
	if ret == 0 then
		QUEST_CHECK(cid);
	end
	
	return ret;
end
